[project]
name = "med-bot"
version = "0.1.0"
description = "Telegram bot"
requires-python = ">=3.10"
dependencies = [
    "aiogram==3.13.1",
    "alembic>=1.13.0",
    "psycopg2>=2.9.11",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv==1.2.1",
    "sqlalchemy>=2.0.45",
]
